# This is a basic workflow to help you get started with Actions

name: ConsoleGitHubActions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - CheckOut branch from GitHub
        uses: actions/checkout@v2

      # JDK Version
      - name: Step 2 = Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
            java-version: 1.8

      # Build Maven Project
      - name: Step 3 - Have GitHub  build Maven Project
        run: mvn test --file /ConsolePrintMessage/ConsolePrint/pom.xml
        
      # List items within Current Directory
      - name: Step 4 - What is in the Current folder?
        run: ls -a
      
      # Step to Understant
      - name : Step 5 - What is the target folder
        run: |
          cd target
          ls -a
      
      
      
      
